Model:
    name: "CANet"
    channel: 256
    output_stride: 16
    pretrained: True
    cuda_device: 0
Train:
    epoch: 240
    lr: 0.0001
    batchsize: 32
    clip: 0.5
    gamma: 0.9
    min_learning_rate: 0.0000001
    warmup_iteration: 300
    shuffle: True
    num_workers: 8
    pin_memory: True
    checkpoint_epoch: 40
    train_path: "data/TrainDataset"
    train_save: "snapshots/CANet-L"
    transforms:
        resize: 
            size: [352, 352]
        random_scale_crop:
            range: [0.75, 1.25]
        random_flip:
            lr: True
            ud: True
        random_rotate:
            range: [0, 359]
        random_image_enhance:
            methods: ['contrast', 'sharpness', 'brightness']
        random_dilation_erosion:
            kernel_range: [2, 5]
        tonumpy: NULL
        normalize: 
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        totensor: NULL
Test:
    gt_path: "data/TestDataset"
    out_path: "results/CANet-L"
    pth_path: "snapshots/CANet-L/latest.pth"
    datasets: ['CVC-300', 'CVC-ClinicDB', 'Kvasir', 'CVC-ColonDB', 'ETIS-LaribPolypDB']
    num_workers: 8
    pin_memory: True
    rot_aug: False
    fg_threshold: 0.5
    transforms:
        resize: 
            size: [352, 352]
        tonumpy: NULL
        normalize: 
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
        totensor: NULL
Eval:
    gt_path: "data/TestDataset"
    pred_path: "results/CANet-L"
    result_path: "EvaluateResults"
    datasets: ['CVC-300', 'CVC-ClinicDB', 'Kvasir', 'CVC-ColonDB', 'ETIS-LaribPolypDB']