# Note that the relative path here are relative to the folder where you run the trainer
data: # Inside each path there are two folders: `images` and `masks` containing inputs and labels
  test_path: './data/test/'
train:
  num_workers: 8
  test_stage: 1 # Either 1 or 2, train the first stage or the second stage
  stage_1_net: 'HarDMSEG' # Stage 1 will be a pretrained model
  stage_2_net: 'MedT' # Stage 2 will be a model whose input is a concatenation of input img & output of stage 1 (no sigmoid)
  batch_size: 8
  input_dim: [512, 512]
  num_channels: 3
  pretrained_path: 'snapshots/MedSeg-best.pt'
